"""Erzeugt segments/<lang>-ind-<branche>.json für die Branchen-Filme (seg.html + seg.js).

python branchen.py   ->  15 Segmentdateien (5 Branchen x en/fr/de)
Nur belegbare Aussagen: keine Zahlen zu Umsatz oder Erfolgsquoten, Beispiel-Lead ist als Beispiel gekennzeichnet.
"""
import json
from pathlib import Path

IDS = ["hook", "tension", "brand", "lead", "exclusive", "weekly", "revenue", "cta", "end"]
PAUSE = [0.6, 0.5, 0.5, 0.45, 0.5, 0.45, 0.5, 0.55, 0.4]
VOICE = {"en": ("bf_emma", 1.0), "fr": ("ff_siwis", 1.08), "de": ("piper:de_DE-thorsten-high", None)}

B = {
 "accountants": {
  "en": {"lines": [
    "Every week, new companies near you choose their accountant. The first practice to call has the best chance.",
    "We spot the moment: new registrations, first payroll, finance roles that stay open.",
    "NextGen Profit brings these companies to you.",
    "Each lead is ready to call: phone, company email, a short profile and a sales tip written for accountants.",
    "And it's yours alone. No other practice in your industry gets the same lead.",
    "Every Monday, fresh leads from your towns arrive in your inbox.",
    "One new client can mean bookkeeping, VAT and payroll for years.",
    "Test it free: ten leads from your area, no strings attached.",
    "NextGen Profit. The right companies, at the right moment."],
   "ui": {"for": "For accountants", "icon": "📊", "first": "✓  Call first, win the client",
    "sig": [["🏛", "New company", "Registered in the last weeks"], ["💷", "First payroll", "First employees on the way"], ["📋", "Finance role open", "Help wanted with the books"]],
    "co": "Northfield Logistics Ltd", "event": "Registered 6 days ago · Stockport", "prio": "High priority",
    "profile": "Transport firm, new director, no accountant yet", "tip": "Offer a fixed-fee start: VAT and payroll",
    "opener": "Congratulations on the new company. Have you chosen an accountant for your first year-end yet?",
    "vals": ["📒  Bookkeeping", "🧾  VAT and payroll", "✓  A client for years"]}},
  "fr": {"lines": [
    "Chaque semaine, de nouvelles entreprises près de chez vous choisissent leur expert-comptable. Le premier cabinet qui appelle a le plus de chances.",
    "Nous repérons le moment : créations, premières embauches, postes en finance qui restent ouverts.",
    "NextGen Profit vous amène ces entreprises.",
    "Chaque piste est prête à appeler : téléphone, e-mail de l'entreprise, un court profil et un conseil de vente pour les experts-comptables.",
    "Et elle n'est qu'à vous. Aucun autre cabinet de votre secteur ne reçoit la même piste.",
    "Chaque lundi, de nouvelles pistes de vos villes arrivent dans votre boîte mail.",
    "Un nouveau client, c'est de la tenue comptable, de la TVA et de la paie pendant des années.",
    "Testez gratuitement : dix pistes de votre zone, sans engagement.",
    "NextGen Profit. Les bonnes entreprises, au bon moment."],
   "ui": {"for": "Pour les experts-comptables", "icon": "📊", "first": "✓  Appeler en premier, gagner le client",
    "sig": [["🏛", "Nouvelle entreprise", "Immatriculée ces dernières semaines"], ["💶", "Première paie", "Premiers salariés en vue"], ["📋", "Poste en finance", "Besoin d'aide pour la comptabilité"]],
    "co": "Transports Rhône Services", "event": "Créée il y a 6 jours · Lyon", "prio": "Priorité haute",
    "profile": "Transport, nouveau dirigeant, pas encore d'expert-comptable", "tip": "Proposer un forfait de démarrage : TVA et paie",
    "opener": "Félicitations pour la création. Avez-vous déjà choisi votre expert-comptable pour le premier bilan ?",
    "vals": ["📒  Tenue comptable", "🧾  TVA et paie", "✓  Un client pour des années"]}},
  "de": {"lines": [
    "Jede Woche wählen neue Unternehmen in Ihrer Nähe ihren Steuerberater. Die Kanzlei, die zuerst anruft, hat die besten Chancen.",
    "Wir erkennen den Moment: Neugründungen, erste Lohnabrechnung, offene Stellen in der Buchhaltung.",
    "NextGen Profit bringt Ihnen diese Unternehmen.",
    "Jeder Lead ist bereit für den Anruf: Telefon, Firmen-E-Mail, Kurzprofil und ein Vertriebstipp für Steuerberater.",
    "Und er gehört nur Ihnen. Keine andere Kanzlei Ihrer Branche bekommt denselben Lead.",
    "Jeden Montag kommen neue Leads aus Ihren Städten in Ihr Postfach.",
    "Ein neuer Mandant bedeutet Buchhaltung, Umsatzsteuer und Lohn über Jahre.",
    "Testen Sie es kostenlos: zehn Leads aus Ihrer Region, unverbindlich.",
    "NextGen Profit. Die richtigen Unternehmen, im richtigen Moment."],
   "ui": {"for": "Für Steuerberater", "icon": "📊", "first": "✓  Zuerst anrufen, Mandant gewinnen",
    "sig": [["🏛", "Neugründung", "In den letzten Wochen eingetragen"], ["💶", "Erste Lohnabrechnung", "Erste Mitarbeitende kommen"], ["📋", "Stelle Buchhaltung", "Hilfe bei den Zahlen gesucht"]],
    "co": "Nordhafen Logistik GmbH", "event": "Vor 6 Tagen eingetragen · Hamburg", "prio": "Hohe Priorität",
    "profile": "Logistik, neuer Geschäftsführer, noch ohne Steuerberater", "tip": "Startpaket anbieten: Umsatzsteuer und Lohn",
    "opener": "Glückwunsch zur Gründung. Haben Sie für Ihren ersten Jahresabschluss schon einen Steuerberater?",
    "vals": ["📒  Buchhaltung", "🧾  Umsatzsteuer und Lohn", "✓  Mandant über Jahre"]}},
 },
 "insurance-brokers": {
  "en": {"lines": [
    "Every new business needs cover before it opens its doors. The broker who calls first gets to quote.",
    "We spot the moment: new companies, first employees, teams that grow fast.",
    "NextGen Profit brings these businesses to you.",
    "Each lead is ready to call: phone, company email, a short profile and a sales tip written for brokers.",
    "And it's yours alone. No other brokerage in your industry gets the same lead.",
    "Every Monday, fresh leads from your towns arrive in your inbox.",
    "One client can mean liability, property and employer cover, renewed year after year.",
    "Test it free: ten leads from your area, no strings attached.",
    "NextGen Profit. The right companies, at the right moment."],
   "ui": {"for": "For insurance brokers", "icon": "🛡️", "first": "✓  First to quote, first to win",
    "sig": [["🏛", "New company", "Needs cover from day one"], ["👥", "First employees", "Employer's liability due"], ["📈", "Fast growth", "Cover no longer fits"]],
    "co": "Brightline Kitchens Ltd", "event": "Registered 9 days ago · Leeds", "prio": "High priority",
    "profile": "Kitchen fitter, new premises, first staff", "tip": "Lead with public and employer's liability",
    "opener": "Congratulations on the new business. Is your liability and employer cover already in place?",
    "vals": ["🛡️  Liability", "🏢  Property and staff", "✓  Renewed every year"]}},
  "fr": {"lines": [
    "Chaque nouvelle entreprise doit être assurée avant d'ouvrir ses portes. Le courtier qui appelle en premier obtient le devis.",
    "Nous repérons le moment : créations, premiers salariés, équipes qui grandissent vite.",
    "NextGen Profit vous amène ces entreprises.",
    "Chaque piste est prête à appeler : téléphone, e-mail de l'entreprise, un court profil et un conseil de vente pour les courtiers.",
    "Et elle n'est qu'à vous. Aucun autre cabinet de courtage de votre secteur ne reçoit la même piste.",
    "Chaque lundi, de nouvelles pistes de vos villes arrivent dans votre boîte mail.",
    "Un client, c'est la responsabilité civile, les locaux et la prévoyance, renouvelés chaque année.",
    "Testez gratuitement : dix pistes de votre zone, sans engagement.",
    "NextGen Profit. Les bonnes entreprises, au bon moment."],
   "ui": {"for": "Pour les courtiers en assurance", "icon": "🛡️", "first": "✓  Premier devis, premier client",
    "sig": [["🏛", "Nouvelle entreprise", "À assurer dès le premier jour"], ["👥", "Premiers salariés", "Prévoyance à mettre en place"], ["📈", "Forte croissance", "Contrats à revoir"]],
    "co": "Cuisines Lumière SAS", "event": "Créée il y a 9 jours · Lyon", "prio": "Priorité haute",
    "profile": "Cuisiniste, nouveaux locaux, premiers salariés", "tip": "Commencer par la RC pro et les locaux",
    "opener": "Félicitations pour la création. Votre responsabilité civile et vos locaux sont-ils déjà assurés ?",
    "vals": ["🛡️  RC professionnelle", "🏢  Locaux et salariés", "✓  Renouvelé chaque année"]}},
  "de": {"lines": [
    "Jedes neue Unternehmen braucht Versicherungsschutz, bevor es startet. Der Makler, der zuerst anruft, darf anbieten.",
    "Wir erkennen den Moment: Neugründungen, erste Mitarbeitende, schnell wachsende Teams.",
    "NextGen Profit bringt Ihnen diese Unternehmen.",
    "Jeder Lead ist bereit für den Anruf: Telefon, Firmen-E-Mail, Kurzprofil und ein Vertriebstipp für Makler.",
    "Und er gehört nur Ihnen. Kein anderes Maklerbüro Ihrer Branche bekommt denselben Lead.",
    "Jeden Montag kommen neue Leads aus Ihren Städten in Ihr Postfach.",
    "Ein Kunde kann Haftpflicht, Inhalt und Mitarbeiterabsicherung bedeuten, Jahr für Jahr verlängert.",
    "Testen Sie es kostenlos: zehn Leads aus Ihrer Region, unverbindlich.",
    "NextGen Profit. Die richtigen Unternehmen, im richtigen Moment."],
   "ui": {"for": "Für Versicherungsmakler", "icon": "🛡️", "first": "✓  Zuerst anbieten, zuerst gewinnen",
    "sig": [["🏛", "Neugründung", "Braucht Schutz ab Tag eins"], ["👥", "Erste Mitarbeitende", "Absicherung wird Thema"], ["📈", "Starkes Wachstum", "Verträge passen nicht mehr"]],
    "co": "Lichtwerk Küchen GmbH", "event": "Vor 9 Tagen eingetragen · Köln", "prio": "Hohe Priorität",
    "profile": "Küchenbauer, neue Räume, erste Mitarbeitende", "tip": "Mit Betriebshaftpflicht einsteigen",
    "opener": "Glückwunsch zur Gründung. Sind Betriebshaftpflicht und Inhalt schon abgesichert?",
    "vals": ["🛡️  Betriebshaftpflicht", "🏢  Inhalt und Personal", "✓  Jedes Jahr verlängert"]}},
 },
 "financial-advisers": {
  "en": {"lines": [
    "New company directors face big money questions: pensions, protection, paying themselves. Few have an adviser yet.",
    "We spot the moment: new directors, first employees, growing teams.",
    "NextGen Profit brings these owners to you.",
    "Each lead is ready to call: phone, company email, a short profile and a sales tip written for advisers.",
    "And it's yours alone. No other advice firm in your industry gets the same lead.",
    "Every Monday, fresh leads from your towns arrive in your inbox.",
    "One director can become a business client and a private client, for many years.",
    "Test it free: ten leads from your area, no strings attached.",
    "NextGen Profit. The right companies, at the right moment."],
   "ui": {"for": "For financial advisers", "icon": "📈", "first": "✓  The right moment for advice",
    "sig": [["🏛", "New director", "Company just set up"], ["👥", "First employees", "Workplace pension due"], ["📈", "Growing team", "Benefits come up"]],
    "co": "Harbour Digital Studio Ltd", "event": "Registered 5 days ago · Manchester", "prio": "High priority",
    "profile": "Digital agency, two new directors", "tip": "Start with director's pay and pension",
    "opener": "Congratulations on the new company. Have you planned how to pay yourselves and your pensions yet?",
    "vals": ["🏦  Pensions", "🛡️  Protection", "✓  Business and private client"]}},
  "fr": {"lines": [
    "Les nouveaux dirigeants ont de grandes questions d'argent : retraite, prévoyance, rémunération. Peu ont déjà un conseiller.",
    "Nous repérons le moment : nouveaux dirigeants, premiers salariés, équipes en croissance.",
    "NextGen Profit vous amène ces dirigeants.",
    "Chaque piste est prête à appeler : téléphone, e-mail de l'entreprise, un court profil et un conseil de vente pour les conseillers.",
    "Et elle n'est qu'à vous. Aucun autre cabinet de conseil de votre secteur ne reçoit la même piste.",
    "Chaque lundi, de nouvelles pistes de vos villes arrivent dans votre boîte mail.",
    "Un dirigeant peut devenir un client professionnel et privé, pour de nombreuses années.",
    "Testez gratuitement : dix pistes de votre zone, sans engagement.",
    "NextGen Profit. Les bonnes entreprises, au bon moment."],
   "ui": {"for": "Pour les conseillers financiers", "icon": "📈", "first": "✓  Le bon moment pour conseiller",
    "sig": [["🏛", "Nouveau dirigeant", "Entreprise tout juste créée"], ["👥", "Premiers salariés", "Prévoyance à organiser"], ["📈", "Équipe en croissance", "Avantages salariés"]],
    "co": "Studio Numérique Presqu'île", "event": "Créée il y a 5 jours · Lyon", "prio": "Priorité haute",
    "profile": "Agence digitale, deux nouveaux dirigeants", "tip": "Commencer par rémunération et retraite",
    "opener": "Félicitations pour la création. Avez-vous déjà réfléchi à votre rémunération et à votre retraite ?",
    "vals": ["🏦  Retraite", "🛡️  Prévoyance", "✓  Client pro et privé"]}},
  "de": {"lines": [
    "Neue Geschäftsführer haben große Geldfragen: Altersvorsorge, Absicherung, das eigene Gehalt. Nur wenige haben schon einen Berater.",
    "Wir erkennen den Moment: neue Geschäftsführer, erste Mitarbeitende, wachsende Teams.",
    "NextGen Profit bringt Ihnen diese Unternehmer.",
    "Jeder Lead ist bereit für den Anruf: Telefon, Firmen-E-Mail, Kurzprofil und ein Vertriebstipp für Berater.",
    "Und er gehört nur Ihnen. Keine andere Beratung Ihrer Branche bekommt denselben Lead.",
    "Jeden Montag kommen neue Leads aus Ihren Städten in Ihr Postfach.",
    "Ein Geschäftsführer kann Firmenkunde und Privatkunde werden, über viele Jahre.",
    "Testen Sie es kostenlos: zehn Leads aus Ihrer Region, unverbindlich.",
    "NextGen Profit. Die richtigen Unternehmen, im richtigen Moment."],
   "ui": {"for": "Für Finanzberater", "icon": "📈", "first": "✓  Der richtige Moment für Beratung",
    "sig": [["🏛", "Neuer Geschäftsführer", "Firma gerade gegründet"], ["👥", "Erste Mitarbeitende", "Betriebsrente wird Thema"], ["📈", "Wachsendes Team", "Benefits gefragt"]],
    "co": "Hafenblick Digital GmbH", "event": "Vor 5 Tagen eingetragen · München", "prio": "Hohe Priorität",
    "profile": "Digitalagentur, zwei neue Geschäftsführer", "tip": "Mit Gehalt und Altersvorsorge einsteigen",
    "opener": "Glückwunsch zur Gründung. Haben Sie Ihr Geschäftsführergehalt und Ihre Altersvorsorge schon geplant?",
    "vals": ["🏦  Altersvorsorge", "🛡️  Absicherung", "✓  Firmen- und Privatkunde"]}},
 },
 "recruitment": {
  "en": {"lines": [
    "Right now, employers near you are struggling to fill roles. Most of them will never call an agency first.",
    "We see it on their own careers pages: roles open for weeks, several hires at once.",
    "NextGen Profit brings these employers to you.",
    "Each lead is ready to call: phone, company email, a short profile and a sales tip written for recruiters.",
    "And it's yours alone. No other agency in your industry gets the same lead.",
    "Every Monday, fresh leads from your towns arrive in your inbox.",
    "One employer with several open roles can mean several placements.",
    "Test it free: ten leads from your area, no strings attached.",
    "NextGen Profit. The right companies, at the right moment."],
   "ui": {"for": "For recruitment agencies", "icon": "🤝", "first": "✓  Call before they give up",
    "sig": [["⏳", "Open 30+ days", "Hard to fill alone"], ["👥", "Several hires", "Three or more roles at once"], ["🔁", "Reposted role", "Same job, again"]],
    "co": "Kestrel Engineering Ltd", "event": "6 roles open · longest 38 days · Bolton", "prio": "High priority",
    "profile": "Engineering firm, growing site team", "tip": "Offer a shortlist for the longest open role",
    "opener": "I saw your maintenance engineer role has been open for a few weeks. Would a shortlist help?",
    "vals": ["📄  One role", "👥  Several placements", "✓  A client who comes back"]}},
  "fr": {"lines": [
    "En ce moment, des employeurs près de chez vous peinent à recruter. La plupart n'appelleront jamais un cabinet d'eux-mêmes.",
    "Nous le voyons sur leurs propres pages carrières : postes ouverts depuis des semaines, plusieurs embauches à la fois.",
    "NextGen Profit vous amène ces employeurs.",
    "Chaque piste est prête à appeler : téléphone, e-mail de l'entreprise, un court profil et un conseil de vente pour les recruteurs.",
    "Et elle n'est qu'à vous. Aucun autre cabinet de votre secteur ne reçoit la même piste.",
    "Chaque lundi, de nouvelles pistes de vos villes arrivent dans votre boîte mail.",
    "Un employeur avec plusieurs postes ouverts peut signifier plusieurs placements.",
    "Testez gratuitement : dix pistes de votre zone, sans engagement.",
    "NextGen Profit. Les bonnes entreprises, au bon moment."],
   "ui": {"for": "Pour les cabinets de recrutement", "icon": "🤝", "first": "✓  Appeler avant qu'ils abandonnent",
    "sig": [["⏳", "Ouvert 30+ jours", "Difficile à pourvoir seul"], ["👥", "Plusieurs embauches", "Trois postes ou plus"], ["🔁", "Offre republiée", "Le même poste, encore"]],
    "co": "Mécanique Faucon SAS", "event": "6 postes ouverts · le plus ancien 38 jours · Villeurbanne", "prio": "Priorité haute",
    "profile": "Industrie, équipe atelier en croissance", "tip": "Proposer une short-list pour le plus ancien poste",
    "opener": "J'ai vu que votre poste de technicien de maintenance est ouvert depuis quelques semaines. Une short-list vous aiderait-elle ?",
    "vals": ["📄  Un poste", "👥  Plusieurs placements", "✓  Un client qui revient"]}},
  "de": {"lines": [
    "Gerade jetzt suchen Arbeitgeber in Ihrer Nähe verzweifelt Personal. Die meisten rufen nie von selbst einen Personalvermittler an.",
    "Wir sehen es auf ihren eigenen Karriereseiten: Stellen, die seit Wochen offen sind, mehrere Einstellungen auf einmal.",
    "NextGen Profit bringt Ihnen diese Arbeitgeber.",
    "Jeder Lead ist bereit für den Anruf: Telefon, Firmen-E-Mail, Kurzprofil und ein Vertriebstipp für Personalvermittler.",
    "Und er gehört nur Ihnen. Keine andere Vermittlung Ihrer Branche bekommt denselben Lead.",
    "Jeden Montag kommen neue Leads aus Ihren Städten in Ihr Postfach.",
    "Ein Arbeitgeber mit mehreren offenen Stellen kann mehrere Vermittlungen bedeuten.",
    "Testen Sie es kostenlos: zehn Leads aus Ihrer Region, unverbindlich.",
    "NextGen Profit. Die richtigen Unternehmen, im richtigen Moment."],
   "ui": {"for": "Für Personalvermittler", "icon": "🤝", "first": "✓  Anrufen, bevor sie aufgeben",
    "sig": [["⏳", "Seit 30+ Tagen offen", "Allein schwer zu besetzen"], ["👥", "Mehrere Stellen", "Drei oder mehr gleichzeitig"], ["🔁", "Erneut ausgeschrieben", "Dieselbe Stelle, wieder"]],
    "co": "Falkenwerk Technik GmbH", "event": "6 offene Stellen · älteste 38 Tage · Dortmund", "prio": "Hohe Priorität",
    "profile": "Maschinenbau, wachsendes Werkstattteam", "tip": "Shortlist für die älteste Stelle anbieten",
    "opener": "Ich habe gesehen, dass Ihre Stelle als Servicetechniker seit einigen Wochen offen ist. Würde Ihnen eine Shortlist helfen?",
    "vals": ["📄  Eine Stelle", "👥  Mehrere Vermittlungen", "✓  Ein Kunde, der wiederkommt"]}},
 },
 "web-agencies": {
  "en": {"lines": [
    "Every week, new companies start trading without a website. The agency that calls first builds it.",
    "We check each new company for a live website, and flag the ones that have none yet.",
    "NextGen Profit brings these businesses to you.",
    "Each lead is ready to call: phone, company email, a short profile and a sales tip written for web agencies.",
    "And it's yours alone. No other agency in your industry gets the same lead.",
    "Every Monday, fresh leads from your towns arrive in your inbox.",
    "A first website often leads to hosting, updates and search work after launch.",
    "Test it free: ten leads from your area, no strings attached.",
    "NextGen Profit. The right companies, at the right moment."],
   "ui": {"for": "For web agencies", "icon": "🌐", "first": "✓  First call, first website",
    "sig": [["🏛", "New company", "Just registered"], ["🔍", "No website found", "Domains checked"], ["📈", "Growing business", "Outgrew its first site"]],
    "co": "Oakridge Home Services Ltd", "event": "Registered 4 days ago · no website found", "prio": "High priority",
    "profile": "Home services, local customers, no site yet", "tip": "Show a simple site with a booking form",
    "opener": "Congratulations on the new company. Would a simple website with online booking help you win your first customers?",
    "vals": ["🌐  Website", "🔧  Hosting and updates", "✓  A client after launch"]}},
  "fr": {"lines": [
    "Chaque semaine, de nouvelles entreprises démarrent sans site web. L'agence qui appelle en premier le construit.",
    "Nous vérifions pour chaque nouvelle entreprise s'il existe un site, et signalons celles qui n'en ont pas encore.",
    "NextGen Profit vous amène ces entreprises.",
    "Chaque piste est prête à appeler : téléphone, e-mail de l'entreprise, un court profil et un conseil de vente pour les agences web.",
    "Et elle n'est qu'à vous. Aucune autre agence de votre secteur ne reçoit la même piste.",
    "Chaque lundi, de nouvelles pistes de vos villes arrivent dans votre boîte mail.",
    "Un premier site mène souvent à l'hébergement, aux mises à jour et au référencement.",
    "Testez gratuitement : dix pistes de votre zone, sans engagement.",
    "NextGen Profit. Les bonnes entreprises, au bon moment."],
   "ui": {"for": "Pour les agences web", "icon": "🌐", "first": "✓  Premier appel, premier site",
    "sig": [["🏛", "Nouvelle entreprise", "Tout juste immatriculée"], ["🔍", "Aucun site trouvé", "Domaines vérifiés"], ["📈", "Entreprise en croissance", "Site de départ dépassé"]],
    "co": "Services Maison Chêne", "event": "Créée il y a 4 jours · aucun site trouvé", "prio": "Priorité haute",
    "profile": "Services à domicile, clientèle locale, pas de site", "tip": "Montrer un site simple avec prise de rendez-vous",
    "opener": "Félicitations pour la création. Un site simple avec prise de rendez-vous vous aiderait-il à trouver vos premiers clients ?",
    "vals": ["🌐  Site web", "🔧  Hébergement et suivi", "✓  Un client après la mise en ligne"]}},
  "de": {"lines": [
    "Jede Woche starten neue Unternehmen ohne Website. Die Agentur, die zuerst anruft, baut sie.",
    "Wir prüfen bei jeder Neugründung, ob es schon eine Website gibt, und markieren die ohne.",
    "NextGen Profit bringt Ihnen diese Unternehmen.",
    "Jeder Lead ist bereit für den Anruf: Telefon, Firmen-E-Mail, Kurzprofil und ein Vertriebstipp für Webagenturen.",
    "Und er gehört nur Ihnen. Keine andere Agentur Ihrer Branche bekommt denselben Lead.",
    "Jeden Montag kommen neue Leads aus Ihren Städten in Ihr Postfach.",
    "Aus der ersten Website werden oft Hosting, Pflege und Suchmaschinenoptimierung.",
    "Testen Sie es kostenlos: zehn Leads aus Ihrer Region, unverbindlich.",
    "NextGen Profit. Die richtigen Unternehmen, im richtigen Moment."],
   "ui": {"for": "Für Webagenturen", "icon": "🌐", "first": "✓  Erster Anruf, erste Website",
    "sig": [["🏛", "Neugründung", "Gerade eingetragen"], ["🔍", "Keine Website gefunden", "Domains geprüft"], ["📈", "Wachsende Firma", "Erste Website zu klein"]],
    "co": "Eichental Hausservice GmbH", "event": "Vor 4 Tagen eingetragen · keine Website gefunden", "prio": "Hohe Priorität",
    "profile": "Hausservice, lokale Kunden, noch keine Website", "tip": "Einfache Website mit Terminbuchung zeigen",
    "opener": "Glückwunsch zur Gründung. Würde Ihnen eine einfache Website mit Online-Terminbuchung bei den ersten Kunden helfen?",
    "vals": ["🌐  Website", "🔧  Hosting und Pflege", "✓  Kunde nach dem Start"]}},
 },
}

if __name__ == "__main__":
    out = Path(__file__).parent / "segments"
    for slug, langs in B.items():
        for lang, c in langs.items():
            voice, speed = VOICE[lang]
            d = {"slug": f"ind/{lang}-{slug}", "lang": lang, "voice": voice, "film": "seg.html", "text": {}, "ui": c["ui"],
                 "script": [{"id": i, "text": t, "pause": p} for i, t, p in zip(IDS, c["lines"], PAUSE)]}
            if speed:
                d["speed"] = speed
            (out / f"{lang}-ind-{slug}.json").write_text(json.dumps(d, ensure_ascii=False, indent=1))
    print("ok")
