-- Startsegmente S1–S8 (CLAUDE.md Abschnitt 4). Bestehende Zeilen bleiben unverändert.
insert into signalwerk.segments (id, name, description, signals, email_countries, status) values
  ('S1', 'Personalvermittlung und Zeitarbeit',
   'Recruiter und Zeitarbeitsfirmen, die Firmen mit schwer besetzbaren Stellen suchen.',
   array['job_open_30d','job_reposted','jobs_3plus','new_location'],
   array['US','UK','IE','NL','SE','BE','FR'], 'idea'),
  ('S2', 'Webagenturen',
   'Agenturen für Website und Online-Auftritt.',
   array['new_incorporation','outdated_website','not_mobile_friendly','new_location'],
   array['US','UK','IE','NL'], 'idea'),
  ('S3', 'IT-Dienstleister / Managed Service Provider',
   'MSPs und IT-Dienstleister für kleine und mittlere Firmen.',
   array['new_location','fast_growth','job_it_admin'],
   array['US','UK','IE','NL'], 'idea'),
  ('S4', 'Gewerbliche Versicherungsmakler',
   'Makler für Betriebs-, Flotten- und Sachversicherungen.',
   array['new_incorporation','expansion','new_fleet','new_warehouse'],
   array['US','UK','IE'], 'idea'),
  ('S5', 'Buchhaltung und Lohnabrechnung',
   'Buchhaltungs-, Steuer- und Payroll-Dienstleister.',
   array['job_accounting','new_incorporation','fast_growth'],
   array['US','UK','IE','NL'], 'idea'),
  ('S6', 'Büroausstattung, Coworking, Gewerbeimmobilien',
   'Anbieter von Büroflächen, Einrichtung und Coworking.',
   array['new_location','hiring_wave','relocation'],
   array['US','UK','NL'], 'idea'),
  ('S7', 'Gebäudereinigung und Facility Services',
   'Reinigungs- und Facility-Dienstleister.',
   array['new_location','new_hall','new_branch'],
   array['US','UK','IE'], 'idea'),
  ('S8', 'Deutschland, alle Segmente',
   'Alle Käufergruppen in Deutschland. Keine E-Mail: nur Anrufliste und Briefvorlage.',
   array['job_open_30d','new_incorporation','new_location','outdated_website'],
   array[]::text[], 'idea'),
  ('S9', 'Finanzberater (unabhängige Finanzberatung, Betriebsrente, Firmenkunden)',
   'Unabhängige Finanzberater und kleine Beratungsfirmen, die Unternehmer und Arbeitgeber beraten.',
   array['new_incorporation','hiring_wave','jobs_3plus','new_location'],
   array['UK','IE','US'], 'idea')
on conflict (id) do nothing;
